=== SubhajitMishra04/web-exam/web.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name" />
                            <xs:element type="xs:integer" name="age" />
                            <xs:element type="xs:integer" name="salary" />
                            <xs:element type="xs:string" name="emailid" />
                            <xs:element type="xs:long" name="phonenum" />
                            <xs:element type="xs:string" name="designation" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="salary">
        <xs:restriction base="xs:integer">
          <xs:minInclusive value="50000"/>
          <xs:maxInclusive value="200000"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== SubhajitMishra04/web-exam/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="web.xsl"?>
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="web.xsd">


    <employee>
        <name>Jim</name>
        <age>32</age>
        <salary>55000</salary>
        <emailid>jim@gmail.com</emailid>
        <phonenum>1234567890</phonenum>
        <designation>Sales</designation>
    </employee>

    <employee>
        <name>Dwight</name>
        <age>35</age>
        <salary>60000</salary>
        <emailid>dwight@gmail.com</emailid>
        <phonenum>2555367459</phonenum>
        <designation>Sales</designation>
    </employee>

    <employee>
        <name>Michael</name>
        <age>40</age>
        <salary>65000</salary>
        <emailid>michael@gmail.com</emailid>
        <phonenum>1324354687</phonenum>
        <designation>Manager</designation>
    </employee>

    <employee>
        <name>Pam</name>
        <age>30</age>
        <salary>51000</salary>
        <emailid>pam@gmail.com</emailid>
        <phonenum>7968574623</phonenum>
        <designation>receptionist</designation>
    </employee>

    <employee>
        <name>oscar</name>
        <age>39</age>
        <salary>55000</salary>
        <emailid>oscar@gmail.com</emailid>
        <phonenum>1559273681</phonenum>
        <designation>accounts</designation>
    </employee>
</company>
